In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
list=[1,2,34,56]
df=pd.DataFrame(list)
df

    0
0   1
1   2
2  34
3  56

In [ ]:
info={
    "name":["Sunil","a","b","c"],
    "mark":[90,67,45,56],
    "cgpa":[9.8,4.5,7.7,2.2]

}
df=pd.DataFrame(info)
df

    name  mark  cgpa
0  Sunil    90   9.8
1      a    67   4.5
2      b    45   7.7
3      c    56   2.2

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
data={
    "name":["Sunil","ankit","bona","chunnu","diya","elza","flizal","greed","horse","dog"],
    "mark":[90,67,45,56,34,65,76,87,56,87],
    "age":[18,19,18,17,19,17,18,18,18,19]

}
df=pd.DataFrame(data)
print(df)

     name  mark  age
0   Sunil    90   18
1   ankit    67   19
2    bona    45   18
3  chunnu    56   17
4    diya    34   19
5    elza    65   17
6  flizal    76   18
7   greed    87   18
8   horse    56   18
9     dog    87   19

In [ ]:
df.shape

(10, 3)

In [ ]:
df.tail(4)

     name  mark  age
6  flizal    76   18
7   greed    87   18
8   horse    56   18
9     dog    87   19

In [ ]:
df.columns

Index(['name', 'mark', 'age'], dtype='object')

In [ ]:
df.rename(columns={'name':'Name','mark':'Mark','age':'Age'},inplace=True)
df.head()

     Name  Mark  Age
0   Sunil    90   18
1   ankit    67   19
2    bona    45   18
3  chunnu    56   17
4    diya    34   19

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Mark    10 non-null     int64
 2   Age     10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

            Mark        Age
count  10.000000  10.000000
mean   66.300000  18.100000
std    18.927053   0.737865
min    34.000000  17.000000
25%    56.000000  18.000000
50%    66.000000  18.000000
75%    84.250000  18.750000
max    90.000000  19.000000

In [ ]:
df.to_csv("student_mark")

In [ ]:
data=pd.read_csv("/content/student_mark")
print(data)

   Unnamed: 0    Name  Mark  Age
0           0   Sunil    90   18
1           1   ankit    67   19
2           2    bona    45   18
3           3  chunnu    56   17
4           4    diya    34   19
5           5    elza    65   17
6           6  flizal    76   18
7           7   greed    87   18
8           8   horse    56   18
9           9     dog    87   19

In [ ]:
data[["Name","Age"]]

     Name  Age
0   Sunil   18
1   ankit   19
2    bona   18
3  chunnu   17
4    diya   19
5    elza   17
6  flizal   18
7   greed   18
8   horse   18
9     dog   19

In [ ]:
data.loc[data.Name=="ankit"]

   Unnamed: 0   Name  Mark  Age
1           1  ankit    67   19

In [ ]:
df.loc[::2]

     Name  Mark  Age
0   Sunil    90   18
2    bona    45   18
4    diya    34   19
6  flizal    76   18
8   horse    56   18

In [ ]:
df_age_filter = df[df["Age"] > 18]
print(df_age_filter)

    Name  Mark  Age
1  ankit    67   19
4   diya    34   19
9    dog    87   19

In [ ]:
df.where(df["Age"]>=18)

     Name  Mark   Age
0   Sunil  90.0  18.0
1   ankit  67.0  19.0
2    bona  45.0  18.0
3     NaN   NaN   NaN
4    diya  34.0  19.0
5     NaN   NaN   NaN
6  flizal  76.0  18.0
7   greed  87.0  18.0
8   horse  56.0  18.0
9     dog  87.0  19.0

In [ ]:
df.where(df["Age"]>=18, other ="not eligible")

           Name          Mark           Age
0         Sunil            90            18
1         ankit            67            19
2          bona            45            18
3  not eligible  not eligible  not eligible
4          diya            34            19
5  not eligible  not eligible  not eligible
6        flizal            76            18
7         greed            87            18
8         horse            56            18
9           dog            87            19

In [ ]:
df["Sub"]=["DAA","PPML","IML","ENG","OS","CSE","DS","COA","ODIA","HINDI"]
df

     Name  Mark  Age    Sub
0   Sunil    90   18    DAA
1   ankit    67   19   PPML
2    bona    45   18    IML
3  chunnu    56   17    ENG
4    diya    34   19     OS
5    elza    65   17    CSE
6  flizal    76   18     DS
7   greed    87   18    COA
8   horse    56   18   ODIA
9     dog    87   19  HINDI

In [ ]:
df=df.drop(df[df.Name=="ABC"].index)

In [ ]:
df.drop(1,axis=0)

     Name  Mark  Age    Sub
0   Sunil    90   18    DAA
2    bona    45   18    IML
3  chunnu    56   17    ENG
4    diya    34   19     OS
5    elza    65   17    CSE
6  flizal    76   18     DS
7   greed    87   18    COA
8   horse    56   18   ODIA
9     dog    87   19  HINDI

In [ ]:
df["percentage"]=(df["Mark"]/100)*100
df

     Name  Mark  Age    Sub  percentage
0   Sunil    90   18    DAA        90.0
1   ankit    67   19   PPML        67.0
2    bona    45   18    IML        45.0
3  chunnu    56   17    ENG        56.0
4    diya    34   19     OS        34.0
5    elza    65   17    CSE        65.0
6  flizal    76   18     DS        76.0
7   greed    87   18    COA        87.0
8   horse    56   18   ODIA        56.0
9     dog    87   19  HINDI        87.0

In [1]:
!git config --global user.name "msunilkumar2025-wq"